### ISSUE TITLE
Netconsole logging not working

### ISSUE THREAD

**Issue by druidu** [rosedu/vmchecker#15]
It should work on Linux, but it doesn't. Log file is empty.

**Comment by calin-iorgulescu** [comment]
I confirm that netconsole logging works at least starting from pull request #71 (but probably did work before that). Now added is the 'KernelMessages' option which can be used to start netcat _before_ starting up the VM, thus capturing the kernel bootup messages. One can also use 'HostCommands' to start netcat _after_ the VM booted up, capturing only the kernel messages issued after, say, a kernel module is loaded.

The config I used, and can confirm works:
- Kernel 3.18.3, netconsole built in the kernel, network card driver built-in as well
- A host-only network interface in VMWare assigned as eth1
- GRUB command line addition: netconsole=10000@192.168.xx.128/eth1,6000@192.168.xx.1/
This will allow the interception of all kernel messages.


Recommend closing this issue.
