### ISSUE TITLE
autologin feature incompatible with nginx + apache deployment

### ISSUE THREAD

**Issue by cojocar** [rosedu/vmchecker#65]
For certain deployments (apache server as a proxy behind nginx), the request will always come from localhost. Anyone can "autologin" with any username.

**Comment by calin-iorgulescu** [comment]
Since #72 , sessions can be persistent. This should, theoretically, reduce the need to login that often when doing development. If you think this suffices, maybe we could remove autologin().

**Comment by valenting** [comment]
Great work, @calin-iorgulescu !
Yes, we can probably remove autologin. Don't worry about the meteor UI, I'll try to fix it soon enugh.
