### ISSUE TITLE
Invalid login can create multiple entries

### ISSUE THREAD

**Issue by neatudarius** [rosedu/vmchecker#92]
Hi,

I have noticed that I can login with any user wich is matched by the regex:
[:multiple_space:]darius.neatu[:multiple_space:]

The problem is that I will have multiple entries for the same subject. For example I have 5 different submissions at PA[1].

![image](https://cloud.githubusercontent.com/assets/8947836/25043651/1fb8b584-212a-11e7-8cd2-4f7590bae8e0.png)
![image](https://cloud.githubusercontent.com/assets/8947836/25043654/2d747168-212a-11e7-8d6f-de3fecf7c95d.png)

Thank you!

Darius-Florentin Neatu

[1] https://vmchecker.cs.pub.ro/ui/#PA

**Comment by razvancrainea** [comment]
Same issue has been reported in #44 and #86.
Looks like this has been addressed upstream, but not yet deployed on vmchecker.cs.pub.ro.

**Comment by cojocar** [comment]
The situation of having things out of sync is a bit bad and will have negative impact in the long term.
AFAIK, we have at least 4 versions of vmchecker: one at UPB, one at VU (https://github.com/cojocar/vmchecker) and one at EPFL (https://github.com/calin-iorgulescu/vmchecker) and one here (main repo, rosedu org). Both of the EPFL and the VU versions seems to be in sync with the main repo.

As the version from UPB has the largest user base it will be nice to have it in sync -- probably this is not possible as things diverged already too much from the github version (correct me if I'm wrong) and things will break.

These problems are actually uncovering a larger problem: we have no testing whatsoever (last commit in the test folder is 7 years old). CI might be the solution but I'm not sure how easy is to test with VMs in, lets say, Travis? I will create another issue to track the testing task. After setting up CI we can think of having some sort of release cycle.

**Comment by valenting** [comment]
The main blocker was that the DBs and config files are no longer
compatible. We should schedule the upgrade sometime in the late summer, and
figure out all the bugs until the semester begins.

**Comment by cojocar** [comment]
Any issue that tracks this problem? Any idea what change introduced this
incompatibility?

**Comment by valenting** [comment]
If I remember it correctly, it's new mandatory fields in the configs that
the old configs miss. This kinda gets transferred to the DBs as well.

**Comment by neatudarius** [comment]
Any updates here? The bug it's not solved yet. :D

**Comment by razvancrainea** [comment]
Not sure if there's anything to update from the dev team, this is a deployment issue - the issue has been fixed years ago, but UPB never deployed the fix.

**Comment by neatudarius** [comment]
Where should I complain about the deployment?😅

**Comment by razvancrainea** [comment]
Not sure there's any point doing so, trust me, I've tried :).
The problem is actually more delicate - as the ticket says, the fix for this issue was made against a version a few years "younger" than the UPB deployment. Therefore, in order to get it fixed, we first need to do a full upgrade of vmchecker (as db and config files are no longer compatible), and unfortunately no one can assume this upgrade.
A different approach would be to backport the fix to the version we are using in UPB, but tbh I don't understand the fix itself to be able to backport it myself. Hence, the compromise to live with the bug :(.

**Comment by razvand** [comment]
@neatudarius , any deployment issues can be sent out to vmchecker-requests@cursuri.cs.pub.ro.

However, as @razvancrainea said, we don't have the resources to upgrade the deployment to include the fix.

**Comment by neatudarius** [comment]
Ok, thank you! Keep in mind this problem for vmck2.
